[Variables]
; Size
Scale=1.00
WidthInput=160
; Settings
CountSection1=5
RefreshRate=60
; Font Name/Color
FontColorMarketTitle=255,255,255,192
FontColorMarketTitlePriceChange=255,204,0,255
FontColorMarketValue=107,198,250,255
FontColorMarketUp=0,255,0,255
FontColorMarketDown=255,0,0,255
; Cryptocurrencies
; 1
Market1=Bitcoin
Market1NumOfDecimals=2
Market1Target=USD
; 2
Market2=Steem
Market2NumOfDecimals=2
Market2Target=LTC
; 3
Market3=Gridcoin
Market3NumOfDecimals=4
Market3Target=USD
; 4
Market4=Bitradio
Market4NumOfDecimals=3
Market4Target=USD
; 5
Market5=Solarcoin
Market5NumOfDecimals=3
Market5Target=USD
; These variables get changed by the skin
Market1GraphBaseValue=0
Market2GraphBaseValue=0
Market3GraphBaseValue=0
Market4GraphBaseValue=0
Market5GraphBaseValue=0
