[Variables]
; Size
Scale=1.00
WidthInput=160
; Settings
CountSection1=5
RefreshRate=300
; Font Name/Color
FontColorMarketTitle=255,255,255,192
FontColorMarketTitlePriceChange=255,204,0,255
FontColorMarketValue=107,198,250,255
FontColorMarketUp=0,255,0,255
FontColorMarketDown=255,0,0,255
; Currencies
; 1
Market1=USD
Market1Target=EUR
; 2
Market2=GBP
Market2Target=EUR
; 3
Market3=EUR
Market3Target=USD
; 4
Market4=JPY
Market4Target=USD
; 5
Market5=XAU
Market5Target=USD
