[Variables]
; Size
Scale=1.00
WidthInput=160
HeightInput=76
WidthEntryViews=320
WidthEurope=480
WidthWorld=800
; Settings
URLInput=https://www.emsc-csem.org/service/rss/rss.php?typ=emsc&map_epicenter=true
RefreshRate=300
CountSection1=4
UseMiles=0
OwnLat=47.5
OwnLong=9.7
WarnMagnitude=4
WarnDistance=100
; Font Name/Color
FontColorTitle=192,192,192,255
FontColorDate=107,198,250,255
FontColorDescription=255,204,0,255
FontColorEarthquakeValues=224,224,224,255
; These variables get changed by the skin
ImageURL=https://www.emsc-csem.org
GlobeTitle=2018-05-21 14:31:46 UTC
EntryViewsTitle=2018-07-21 16:47:14 UTC
