[Variables]
; Size
Scale=1.00
Opacity=255
WidthInput=160
HeightInput=76
WidthEntryViews=160
WidthEurope=320
WidthWorld=320
; Settings
URLInput=https://www.emsc-csem.org/service/rss/rss.php?typ=emsc&map_epicenter=true
RefreshRate=300
CountSection1=4
UseMiles=0
OwnLat=47.5
OwnLong=9.7
WarnMagnitude=4
WarnDistance=100
; Font Name/Color
FontColorTitle=192,192,192,255
FontColorDate=107,198,250,255
FontColorDescription=255,204,0,255
FontColorEarthquakeValues=224,224,224,255
; These variables get changed by the skin
ImageURL=https://www.emsc-csem.org/Images/EVID/72/724/724495/724495.global.thumb.jpg
GlobeTitle=2018-05-21 14:31:46 UTC
EntryViewsTitle=2018-11-10 14:11:54 UTC
