[Variables]
; Size
Scale=1.00
WidthInput=160
; Settings
IgnoreProcesses=_Total|Idle|dwm|wmpnetwk|csrss|svchost|lsass|System|wininit|ns
OnlyProcesses=
GroupProcesses=1
CountCPU=5
CountRAM=5
CountGPU=5
CountVRAM=5
CountIORead=4
CountIOWrite=4
CountCustom=5
; Custom
CustomEnable=1
CustomName=Working Set
CustomCategory=Process 
CustomCounter=Working Set
CustomPercent=0
CustomAppend=B
CustomColor=255,255,128,255
