[Variables]
type=user
CPIDuser=b83eea2f1c0c73114bc616569deb568d
CPIDteam=05d4b63c40a4d8c2b3dd2180f656931f
CPIDhost=22ddcbab851cecce80f2a3a673832ccd
CountProjects=10
Project1=BOINC combined
Project2=Collatz Conjecture
Project3=Amicable Numbers
Project4=POGS (theSkyNet)
Project5=SRBase
Project6=NFS@Home
Project7=Moo! Wrapper
Project8=MilkyWay@home
Project9=DrugDiscovery@Home
Project10=NumberFields@home
; Settings
Height=385
Width=146
ProjectsWidth=700
typeUser=1
typeTeam=0
typeHost=0
CPID=b83eea2f1c0c73114bc616569deb568d
Country=Austria
