[Variables]
; Languages Variables
PerfMonDisplayColumnEN=Name
PerfMonDisplayColumnDE=Name
PerfMonDisplayColumnFR=nom de l'image
PerfMonDisplayColumnCustom='Name'
PerfMonIndicatorRootEN=Process
PerfMonIndicatorRootDE=Prozess
PerfMonIndicatorRootFR=Processus
PerfMonIndicatorRootCustom=Prozess
PerfMonIndicatorSecondCpuEN=% Processor Time
PerfMonIndicatorSecondCpuDE=Prozessorzeit (%)
PerfMonIndicatorSecondCpuFR=% temps processeur
PerfMonIndicatorSecondCpuCustom=Prozessorzeit (%)
PerfMonIndicatorSecondRamEN=Working Set - Private
PerfMonIndicatorSecondRamDE=Arbeitsseiten - privat
PerfMonIndicatorSecondRamFR=Plage de travail - Privée
PerfMonIndicatorSecondRamCustom=Arbeitsseiten
; Language Settings
lang=EN
langEN=1
langDE=0
langFR=0
langCustom=0
; Settings
Height=235
Width=146
CountCPU=10
CountRAM=10
RefreshRate=1000
