; IOReadRepeat#
[MeterIOReadRepeat#Background]
Meter=Image
MeterStyle=StyleDefault | StyleDisabled | StyleScale | StyleLoadingHide | StyleSeparator | StyleSeparatorOdd | StyleTableRowBackground

[MeterIOReadRepeat#Name]
Meter=String
MeasureName=MeasureIOReadRepeat#
MeterStyle=StyleDefault | StyleScale | StyleIOReadName | StyleTableRow | StyleLoadingHide

[MeterIOReadRepeat#Value]
Meter=String
MeasureName=MeasureIOReadRepeat#ForScaling
MeterStyle=StyleDefault | StyleScale | StyleIOReadValue | StyleTableRowValue | StyleLoadingHide
