; CPURepeat#
[MeterCPURepeat#Background]
Meter=Image
MeterStyle=StyleDefault | StyleDisabled | StyleScale | StyleLoadingHide | StyleSeparator | StyleSeparatorOdd | StyleTableRowBackground

[MeterCPURepeat#Name]
Meter=String
MeasureName=MeasureCPURepeat#
MeterStyle=StyleDefault | StyleScale | StyleCPUName | StyleTableRow | StyleLoadingHide

[MeterCPURepeat#Value]
Meter=String
MeasureName=MeasureCPURepeat#ForScaling
MeterStyle=StyleDefault | StyleScale | StyleCPUValue | StyleTableRowValue | StyleLoadingHide
