; VRAMRepeat#
[MeterVRAMRepeat#Background]
Meter=Image
MeterStyle=StyleDefault | StyleDisabled | StyleScale | StyleLoadingHide | StyleSeparator | StyleSeparatorOdd | StyleTableRowBackground

[MeterVRAMRepeat#Name]
Meter=String
MeasureName=MeasureVRAMRepeat#
MeterStyle=StyleDefault | StyleScale | StyleVRAMName | StyleTableRow | StyleLoadingHide

[MeterVRAMRepeat#Value]
Meter=String
MeasureName=MeasureVRAMRepeat#ForScaling
MeterStyle=StyleDefault | StyleScale | StyleVRAMValue | StyleTableRowValue | StyleLoadingHide