; RAMRepeat#
[MeterRAMRepeat#Background]
Meter=Image
MeterStyle=StyleDefault | StyleDisabled | StyleScale | StyleLoadingHide | StyleSeparator | StyleSeparatorOdd | StyleTableRowBackground

[MeterRAMRepeat#Name]
Meter=String
MeasureName=MeasureRAMRepeat#
MeterStyle=StyleDefault | StyleScale | StyleRAMName | StyleTableRow | StyleLoadingHide

[MeterRAMRepeat#Value]
Meter=String
MeasureName=MeasureRAMRepeat#ForScaling
MeterStyle=StyleDefault | StyleScale | StyleRAMValue | StyleTableRowValue | StyleLoadingHide