; GPURepeat#
[MeterGPURepeat#Background]
Meter=Image
MeterStyle=StyleDefault | StyleDisabled | StyleScale | StyleLoadingHide | StyleSeparator | StyleSeparatorOdd | StyleTableRowBackground

[MeterGPURepeat#Name]
Meter=String
MeasureName=MeasureGPURepeat#
MeterStyle=StyleDefault | StyleScale | StyleGPUName | StyleTableRow | StyleLoadingHide

[MeterGPURepeat#Value]
Meter=String
MeasureName=MeasureGPURepeat#ForScaling
MeterStyle=StyleDefault | StyleScale | StyleGPUValue | StyleTableRowValue | StyleLoadingHide