; IOWriteRepeat#
[MeterIOWriteRepeat#Background]
Meter=Image
MeterStyle=StyleDefault | StyleDisabled | StyleScale | StyleLoadingHide | StyleSeparator | StyleSeparatorOdd | StyleTableRowBackground

[MeterIOWriteRepeat#Name]
Meter=String
MeasureName=MeasureIOWriteRepeat#
MeterStyle=StyleDefault | StyleScale | StyleIOWriteName | StyleTableRow | StyleLoadingHide

[MeterIOWriteRepeat#Value]
Meter=String
MeasureName=MeasureIOWriteRepeat#ForScaling
MeterStyle=StyleDefault | StyleScale | StyleIOWriteValue | StyleTableRowValue | StyleLoadingHide
