; CustomRepeat#
[MeterCustomRepeat#Background]
Meter=Image
MeterStyle=StyleDefault | StyleDisabled | StyleScale | StyleLoadingHide | StyleSeparator | StyleSeparatorOdd | StyleTableRowBackground

[MeterCustomRepeat#Name]
Meter=String
MeasureName=MeasureCustomRepeat#
MeterStyle=StyleDefault | StyleScale | StyleCustomName | StyleTableRow | StyleLoadingHide

[MeterCustomRepeat#Value]
Meter=String
MeasureName=MeasureCustomRepeat#ForScaling
MeterStyle=StyleDefault | StyleScale | StyleCustomValue | StyleTableRowValue | StyleLoadingHide
